spring.application.name=guias-despacho-cloud

server.port= 8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


spring.datasource.url=jdbc:h2:mem:guias_despacho_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Configuracion AWS S3
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_BUCKET_NAME:tu-bucket-guias-despacho}

aws.access-key-id=${AWS_ACCESS_KEY_ID:tu_access_key_local}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:tu_secret_key_local}
aws.session-token=${AWS_SESSION_TOKEN:}

#Configuracion EFS
${EFS_MOUNT_PATH:/mnt/efs/guias-temporales/}

#Configuracion Azure AD
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://duocabdul.b2clogin.com/tfp/4cae276d-1be3-4ff3-ae0c-01abba2853e3/b2c_1_duocdemoazure_registro_login/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://duocabdul.b2clogin.com/duocabdul.onmicrosoft.com/b2c_1_duocdemoazure_registro_login/discovery/v2.0/keys

#Configuracion RabbitMQ

spring.rabbitmq.host=100.26.113.36
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#Configuracion de Errores de RabbitMQ
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
